name: Go
on:
  push:
    branches: [ main ]
    tags:
      - 'v*'
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.17

    - name: Test
      run: go test -v ./...

    - name: Build linux64
      run: GOOS=linux GOARCH=amd64 go build -o consul-port-redirector-linux-amd64 -v ./...

    - name: Build darwin64
      run: GOOS=darwin GOARCH=amd64 go build -o consul-port-redirector-darwin-amd64 -v ./...

    - uses: actions/upload-artifact@v3
      with:
        name: consul-port-redirector-linux-amd64
        path: consul-port-redirector-linux-amd64

    - uses: actions/upload-artifact@v3
      with:
        name: consul-port-redirector-darwin-amd64
        path: consul-port-redirector-darwin-amd64
